/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.GamesDAO;
import javabens.Games;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nilce
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIdade1 = new javax.swing.JPanel();
        jcb1 = new javax.swing.JCheckBox();
        jcb2 = new javax.swing.JCheckBox();
        codigo = new javax.swing.JLabel();
        jrbF = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        sexo = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        quantidade = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        jrbM = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbRPG = new javax.swing.JRadioButton();
        rbMOBA = new javax.swing.JRadioButton();
        rbMMORPG = new javax.swing.JRadioButton();
        rbEstrategia = new javax.swing.JRadioButton();
        rbAventura = new javax.swing.JRadioButton();
        rbCorrida = new javax.swing.JRadioButton();
        rbAcao = new javax.swing.JRadioButton();
        rbEsportes = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cxPC = new javax.swing.JCheckBox();
        cxXboxOne = new javax.swing.JCheckBox();
        cxXboxOneS = new javax.swing.JCheckBox();
        cxPS4 = new javax.swing.JCheckBox();
        cxPS4Pro = new javax.swing.JCheckBox();
        txtNome = new javax.swing.JTextField();
        codigo1 = new javax.swing.JLabel();
        txtCodigo1 = new javax.swing.JTextField();
        btnNovo1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        jpIdade1.setBackground(new java.awt.Color(255, 255, 255));
        jpIdade1.setBorder(new javax.swing.border.MatteBorder(null));

        jcb1.setBackground(new java.awt.Color(255, 255, 255));
        jcb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcb1.setForeground(new java.awt.Color(0, 102, 51));
        jcb1.setText("jCheckBox1");
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jcb2.setBackground(new java.awt.Color(255, 255, 255));
        jcb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcb2.setForeground(new java.awt.Color(0, 102, 51));
        jcb2.setText("jCheckBox2");

        javax.swing.GroupLayout jpIdade1Layout = new javax.swing.GroupLayout(jpIdade1);
        jpIdade1.setLayout(jpIdade1Layout);
        jpIdade1Layout.setHorizontalGroup(
            jpIdade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIdade1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jcb1)
                .addGap(47, 47, 47)
                .addComponent(jcb2)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jpIdade1Layout.setVerticalGroup(
            jpIdade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIdade1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIdade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb1)
                    .addComponent(jcb2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setForeground(new java.awt.Color(0, 102, 51));
        codigo.setText("Codigo:");

        jrbF.setBackground(new java.awt.Color(255, 255, 255));
        jrbF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbF.setForeground(new java.awt.Color(0, 102, 51));
        jrbF.setText("F");
        jrbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 102, 51));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        sexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexo.setForeground(new java.awt.Color(0, 102, 51));
        sexo.setText("Sexo:");

        btnNovo.setBackground(new java.awt.Color(153, 153, 153));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(0, 102, 51));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        quantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantidade.setForeground(new java.awt.Color(0, 102, 51));
        quantidade.setText("Quantidade");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtCodigo.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Cadastro de Bovinos");

        txtQuantidade.setToolTipText("");
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Data de registro:");

        idade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idade.setForeground(new java.awt.Color(0, 102, 51));
        idade.setText("Classificacao da Idade");

        jrbM.setBackground(new java.awt.Color(255, 255, 255));
        jrbM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbM.setForeground(new java.awt.Color(0, 102, 51));
        jrbM.setText("M");
        jrbM.setToolTipText("");
        jrbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");

        txtTamanho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Genero:");

        txtFabricante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Plataforma:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tamanho:");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        rbRPG.setBackground(new java.awt.Color(204, 204, 204));
        rbRPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbRPG.setText("RPG");

        rbMOBA.setBackground(new java.awt.Color(204, 204, 204));
        rbMOBA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbMOBA.setText("MOBA");

        rbMMORPG.setBackground(new java.awt.Color(204, 204, 204));
        rbMMORPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbMMORPG.setText("MMORPG");

        rbEstrategia.setBackground(new java.awt.Color(204, 204, 204));
        rbEstrategia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbEstrategia.setText("Estrategia");
        rbEstrategia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEstrategiaActionPerformed(evt);
            }
        });

        rbAventura.setBackground(new java.awt.Color(204, 204, 204));
        rbAventura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbAventura.setText("Aventura");
        rbAventura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAventuraActionPerformed(evt);
            }
        });

        rbCorrida.setBackground(new java.awt.Color(204, 204, 204));
        rbCorrida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbCorrida.setText("Corrida");

        rbAcao.setBackground(new java.awt.Color(204, 204, 204));
        rbAcao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbAcao.setText("Ação");

        rbEsportes.setBackground(new java.awt.Color(204, 204, 204));
        rbEsportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbEsportes.setText("Esporte");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbAcao)
                        .addGap(27, 27, 27)
                        .addComponent(rbAventura)
                        .addGap(27, 27, 27)
                        .addComponent(rbEstrategia)
                        .addGap(17, 17, 17)
                        .addComponent(rbRPG))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbEsportes)
                        .addGap(27, 27, 27)
                        .addComponent(rbCorrida)
                        .addGap(27, 27, 27)
                        .addComponent(rbMMORPG)
                        .addGap(17, 17, 17)
                        .addComponent(rbMOBA)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAcao)
                    .addComponent(rbAventura)
                    .addComponent(rbEstrategia)
                    .addComponent(rbRPG))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbEsportes)
                    .addComponent(rbCorrida)
                    .addComponent(rbMMORPG)
                    .addComponent(rbMOBA))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Fabricante:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cxPC.setBackground(new java.awt.Color(204, 204, 204));
        cxPC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxPC.setText("PC");

        cxXboxOne.setBackground(new java.awt.Color(204, 204, 204));
        cxXboxOne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxXboxOne.setText("Xbox One");
        cxXboxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxXboxOneActionPerformed(evt);
            }
        });

        cxXboxOneS.setBackground(new java.awt.Color(204, 204, 204));
        cxXboxOneS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxXboxOneS.setText("Xbox one X");

        cxPS4.setBackground(new java.awt.Color(204, 204, 204));
        cxPS4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxPS4.setText("PS4");

        cxPS4Pro.setBackground(new java.awt.Color(204, 204, 204));
        cxPS4Pro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxPS4Pro.setText("PS4 Pro");
        cxPS4Pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPS4ProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cxPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cxXboxOne)
                .addGap(18, 18, 18)
                .addComponent(cxXboxOneS)
                .addGap(18, 18, 18)
                .addComponent(cxPS4)
                .addGap(18, 18, 18)
                .addComponent(cxPS4Pro)
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxPC)
                    .addComponent(cxXboxOne)
                    .addComponent(cxXboxOneS)
                    .addComponent(cxPS4)
                    .addComponent(cxPS4Pro))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        codigo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo1.setText("Codigo:");

        txtCodigo1.setEditable(false);
        txtCodigo1.setText("*********");

        btnNovo1.setBackground(new java.awt.Color(153, 153, 153));
        btnNovo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo1.setText("Novo");
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });

        btnSalvar1.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel8.setText("Cadastro de Games");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("GB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(codigo1)
                        .addGap(26, 26, 26)
                        .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnSalvar1)
                        .addGap(35, 35, 35)
                        .addComponent(btnNovo1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo1)
                    .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar1)
                    .addComponent(btnNovo1))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Genero", "Plataforma", "Tamanho", "Fabricante"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Código:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jLayeredPane1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jrbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFActionPerformed

    private void jrbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrbMActionPerformed

    private void rbEstrategiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEstrategiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEstrategiaActionPerformed

    private void rbAventuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAventuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAventuraActionPerformed

    private void cxXboxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxXboxOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxXboxOneActionPerformed

    private void cxPS4ProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPS4ProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPS4ProActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        // botao novo
        this.rbAcao.setSelected(false);
        this.rbAventura.setSelected(false);
        this.rbRPG.setSelected(false);
        this.rbCorrida.setSelected(false);
        this.rbEsportes.setSelected(false);
        this.rbEstrategia.setSelected(false);
        this.rbMMORPG.setSelected(false);
        this.rbMOBA.setSelected(false);

        this.cxPC.setSelected(false);
        this.cxXboxOne.setSelected(false);
        this.cxXboxOneS.setSelected(false);
        this.cxPS4.setSelected(false);
        this.cxPS4Pro.setSelected(false);

        this.txtTamanho.setText("");
        this.txtFabricante.setText("");
        this.txtNome.setText("");

    }//GEN-LAST:event_btnNovo1ActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        // botao salvar
        try {
            Games obj = new Games();

            if(rbAcao.isSelected()){
                obj.setGenero(rbAcao.getText());
            }
            if(rbAventura.isSelected()){
                obj.setGenero(rbAventura.getText());
            }
            if(rbEstrategia.isSelected()){
                obj.setGenero(rbEstrategia.getText());
            }
            if(rbRPG.isSelected()){
                obj.setGenero(rbRPG.getText());
            }
            if(rbEsportes.isSelected()){
                obj.setGenero(rbEsportes.getText());
            }
            if(rbCorrida.isSelected()){
                obj.setGenero(rbCorrida.getText());
            }
            if(rbMMORPG.isSelected()){
                obj.setGenero(rbMMORPG.getText());
            }
            if(rbMOBA.isSelected()){
                obj.setGenero(rbMOBA.getText());
            }
            //-------------------------------
            if(cxPC.isSelected()){
                obj.setPlataforma(cxPC.getText());
            }
            if(cxXboxOne.isSelected()){
                obj.setPlataforma(cxXboxOne.getText());
            }
            if(cxXboxOneS.isSelected()){
                obj.setPlataforma(cxXboxOneS.getText());
            }
            if(cxPS4.isSelected()){
                obj.setPlataforma(cxPS4.getText());
            }
            if(cxPS4Pro.isSelected()){
                obj.setPlataforma(cxPS4Pro.getText());
            }

            obj.setTamanho((float) Double.parseDouble(txtTamanho.getText()));
            obj.setFabricante(txtFabricante.getText());
            obj.setNome(txtNome.getText());

            //criar objeto tipo cliente DAO

            GamesDAO dao = new GamesDAO();
            dao.cadastrarGames(obj);

            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null,"Erro" + erro);
        }

    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel codigo1;
    private javax.swing.JCheckBox cxPC;
    private javax.swing.JCheckBox cxPS4;
    private javax.swing.JCheckBox cxPS4Pro;
    private javax.swing.JCheckBox cxXboxOne;
    private javax.swing.JCheckBox cxXboxOneS;
    private javax.swing.JLabel idade;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox jcb1;
    private javax.swing.JCheckBox jcb2;
    private javax.swing.JPanel jpIdade1;
    private javax.swing.JRadioButton jrbF;
    private javax.swing.JRadioButton jrbM;
    private javax.swing.JLabel quantidade;
    private javax.swing.JRadioButton rbAcao;
    private javax.swing.JRadioButton rbAventura;
    private javax.swing.JRadioButton rbCorrida;
    private javax.swing.JRadioButton rbEsportes;
    private javax.swing.JRadioButton rbEstrategia;
    private javax.swing.JRadioButton rbMMORPG;
    private javax.swing.JRadioButton rbMOBA;
    private javax.swing.JRadioButton rbRPG;
    private javax.swing.JLabel sexo;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTamanho;
    // End of variables declaration//GEN-END:variables
}
