/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.GamesDAO;
import javabens.Games;
import javax.swing.JOptionPane;

/**
 *
 * @author nilce
 */
public class TelaCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbRPG = new javax.swing.JRadioButton();
        rbMOBA = new javax.swing.JRadioButton();
        rbMMORPG = new javax.swing.JRadioButton();
        rbEstrategia = new javax.swing.JRadioButton();
        rbAventura = new javax.swing.JRadioButton();
        rbCorrida = new javax.swing.JRadioButton();
        rbAcao = new javax.swing.JRadioButton();
        rbEsportes = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        cxPC = new javax.swing.JCheckBox();
        cxXboxOne = new javax.swing.JCheckBox();
        cxXboxOneS = new javax.swing.JCheckBox();
        cxPS4 = new javax.swing.JCheckBox();
        cxPS4Pro = new javax.swing.JCheckBox();
        txtTamanho = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Cadastro");

        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setText("Codigo:");

        txtCodigo.setEditable(false);
        txtCodigo.setText("*********");

        btnNovo.setBackground(new java.awt.Color(153, 153, 153));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel2.setText("Cadastro de Games");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Genero:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Plataforma:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tamanho:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fabricante:");

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        rbRPG.setBackground(new java.awt.Color(204, 204, 204));
        rbRPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbRPG.setText("RPG");

        rbMOBA.setBackground(new java.awt.Color(204, 204, 204));
        rbMOBA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbMOBA.setText("MOBA");

        rbMMORPG.setBackground(new java.awt.Color(204, 204, 204));
        rbMMORPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbMMORPG.setText("MMORPG");

        rbEstrategia.setBackground(new java.awt.Color(204, 204, 204));
        rbEstrategia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbEstrategia.setText("Estrategia");
        rbEstrategia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEstrategiaActionPerformed(evt);
            }
        });

        rbAventura.setBackground(new java.awt.Color(204, 204, 204));
        rbAventura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbAventura.setText("Aventura");
        rbAventura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAventuraActionPerformed(evt);
            }
        });

        rbCorrida.setBackground(new java.awt.Color(204, 204, 204));
        rbCorrida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbCorrida.setText("Corrida");

        rbAcao.setBackground(new java.awt.Color(204, 204, 204));
        rbAcao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbAcao.setText("Ação");

        rbEsportes.setBackground(new java.awt.Color(204, 204, 204));
        rbEsportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbEsportes.setText("Esporte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbAcao)
                        .addGap(27, 27, 27)
                        .addComponent(rbAventura)
                        .addGap(27, 27, 27)
                        .addComponent(rbEstrategia)
                        .addGap(17, 17, 17)
                        .addComponent(rbRPG))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbEsportes)
                        .addGap(27, 27, 27)
                        .addComponent(rbCorrida)
                        .addGap(27, 27, 27)
                        .addComponent(rbMMORPG)
                        .addGap(17, 17, 17)
                        .addComponent(rbMOBA)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAcao)
                    .addComponent(rbAventura)
                    .addComponent(rbEstrategia)
                    .addComponent(rbRPG))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbEsportes)
                    .addComponent(rbCorrida)
                    .addComponent(rbMMORPG)
                    .addComponent(rbMOBA))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cxPC.setBackground(new java.awt.Color(204, 204, 204));
        cxPC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxPC.setText("PC");

        cxXboxOne.setBackground(new java.awt.Color(204, 204, 204));
        cxXboxOne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxXboxOne.setText("Xbox One");
        cxXboxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxXboxOneActionPerformed(evt);
            }
        });

        cxXboxOneS.setBackground(new java.awt.Color(204, 204, 204));
        cxXboxOneS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxXboxOneS.setText("Xbox one S");

        cxPS4.setBackground(new java.awt.Color(204, 204, 204));
        cxPS4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxPS4.setText("PS4");

        cxPS4Pro.setBackground(new java.awt.Color(204, 204, 204));
        cxPS4Pro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cxPS4Pro.setText("PS4 Pro");
        cxPS4Pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPS4ProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cxPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cxXboxOne)
                .addGap(18, 18, 18)
                .addComponent(cxXboxOneS)
                .addGap(18, 18, 18)
                .addComponent(cxPS4)
                .addGap(18, 18, 18)
                .addComponent(cxPS4Pro)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxPC)
                    .addComponent(cxXboxOne)
                    .addComponent(cxXboxOneS)
                    .addComponent(cxPS4)
                    .addComponent(cxPS4Pro))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        txtTamanho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtFabricante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(codigo)
                        .addGap(26, 26, 26)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnSalvar)
                        .addGap(35, 35, 35)
                        .addComponent(btnNovo)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // botao salvar
        try {
            Games obj = new Games();
            
        if(rbAcao.isSelected()){
            obj.setGenero(rbAcao.getText());
        }
        if(rbAventura.isSelected()){
            obj.setGenero(rbAventura.getText());
        }
        if(rbEstrategia.isSelected()){
            obj.setGenero(rbEstrategia.getText());
        }
        if(rbRPG.isSelected()){
            obj.setGenero(rbRPG.getText());
        }
        if(rbEsportes.isSelected()){
            obj.setGenero(rbEsportes.getText());
        }
        if(rbCorrida.isSelected()){
            obj.setGenero(rbCorrida.getText());
        }
        if(rbMMORPG.isSelected()){
            obj.setGenero(rbMMORPG.getText());
        }
        if(rbMOBA.isSelected()){
            obj.setGenero(rbMOBA.getText());
        }
        //-------------------------------
        if(cxPC.isSelected()){
            obj.setPlataforma(cxPC.getText());
        }
        if(cxXboxOne.isSelected()){
            obj.setPlataforma(cxXboxOne.getText());
        }
        if(cxXboxOneS.isSelected()){
            obj.setPlataforma(cxXboxOneS.getText());
        }
        if(cxPS4.isSelected()){
            obj.setPlataforma(cxPS4.getText());
        }
        if(cxPS4Pro.isSelected()){
            obj.setPlataforma(cxPS4Pro.getText());
        }
        
        obj.setTamanho((float) Double.parseDouble(txtTamanho.getText()));
        obj.setFabricante(txtFabricante.getText());
        obj.setNome(txtNome.getText());
        
        //criar objeto tipo cliente DAO
        
        GamesDAO dao = new GamesDAO();
        dao.cadastrarGames(obj);
        
        JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
        
        } catch (Exception erro) {
            
            JOptionPane.showMessageDialog(null,"Erro" + erro);
        }
        
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // botao novo
        this.rbAcao.setSelected(false);
        this.rbAventura.setSelected(false);
        this.rbRPG.setSelected(false);
        this.rbCorrida.setSelected(false);
        this.rbEsportes.setSelected(false);
        this.rbEstrategia.setSelected(false);
        this.rbMMORPG.setSelected(false);
        this.rbMOBA.setSelected(false);
        
        
        
        this.cxPC.setSelected(false);
        this.cxXboxOne.setSelected(false);
        this.cxXboxOneS.setSelected(false);
        this.cxPS4.setSelected(false);
        this.cxPS4Pro.setSelected(false);
        
        
        this.txtTamanho.setText("");
        this.txtFabricante.setText("");
        this.txtNome.setText("");
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cxXboxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxXboxOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxXboxOneActionPerformed

    private void cxPS4ProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPS4ProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPS4ProActionPerformed

    private void rbAventuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAventuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAventuraActionPerformed

    private void rbEstrategiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEstrategiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEstrategiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel codigo;
    private javax.swing.JCheckBox cxPC;
    private javax.swing.JCheckBox cxPS4;
    private javax.swing.JCheckBox cxPS4Pro;
    private javax.swing.JCheckBox cxXboxOne;
    private javax.swing.JCheckBox cxXboxOneS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbAcao;
    private javax.swing.JRadioButton rbAventura;
    private javax.swing.JRadioButton rbCorrida;
    private javax.swing.JRadioButton rbEsportes;
    private javax.swing.JRadioButton rbEstrategia;
    private javax.swing.JRadioButton rbMMORPG;
    private javax.swing.JRadioButton rbMOBA;
    private javax.swing.JRadioButton rbRPG;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTamanho;
    // End of variables declaration//GEN-END:variables
}
